CI: Apparently setup-beam requires this now
Otherwise it complains:
  Run erlef/setup-beam@v1
  Error: Tried to map a target OS from env. variable 'ImageOS'
    (got ubuntu24-arm64), but failed. If you're using a self-hosted runner,
    you should set 'env': 'ImageOS': ... to one of the following:
    ['ubuntu22', 'ubuntu24', 'win19', 'win22', 'win25', 'macos13',
     'macos14', 'macos15', 'macos26']